spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elearn
    username: elearn
    password: elearn
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 8080

app:
  jwt:
    # generate a long random string once: openssl rand -base64 48
    secret: "tfAVyItWEHlPF7id8gibegE8yF/y1T7wcbWnyD4Pkjsq7SdZRCf9d1BDGINsMrrS"
    access-exp-min: 30
    refresh-exp-days: 7
