spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elearn
    username: elearn
    password: elearn
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 8080

app:
  jwt:
    # generate a long random string once: openssl rand -base64 48
    secret: "change-me-to-a-long-random-secret-string"
    access-exp-min: 30
    refresh-exp-days: 7
