CREATE TABLE IF NOT EXISTS quiz (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(255),
  lesson_id BIGINT NOT NULL REFERENCES lesson(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS quiz_question (
  id BIGSERIAL PRIMARY KEY,
  question TEXT NOT NULL,
  correct_answer TEXT,
  quiz_id BIGINT NOT NULL REFERENCES quiz(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS quiz_submission (
  id BIGSERIAL PRIMARY KEY,
  answer TEXT,
  correct BOOLEAN NOT NULL,
  question_id BIGINT NOT NULL REFERENCES quiz_question(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
